Repository wncc/instiapp-api, pull requests merged in 2019-01, with the labels that each got.

#319 Prevent news notification spam
  .coveragerc
  news/management/commands/news_chore.py
  news/migrations/0007_newsentry_notify.py
  news/models.py
  news/test/sample-feed-1.xml
  news/test/sample-feed-2.xml
  news/test/sample-feed-3.xml
  news/test/test_server.py
  news/tests.py
  other/notifications.py
  other/tests.py
Labels: priority2: important, sec: chores, sec: news-feed, sec: testing, type: bug/fix

#321 chore(deps): Update requirements
  requirements.txt
Labels: type: chore

#322 fix(venter): Use django.conf.settings for COMPLAINT_AUTO_SUBSCRIBE
  venter/views.py
Labels: sec: venter, severity3: broken, type: bug/fix

#327 fix(fcm): Add click_action to data message for flutter
  helpers/fcm.py
  other/models.py
  users/tests.py
Labels: sec: FCM, type: bug/fix

#329 chore(deps): Remove PyYAML from requirements
  requirements.txt
Labels: type: chore

#331 fix(fcm): Prevent crash when click_action isn't present in data_message
  helpers/fcm.py
  other/models.py
  users/tests.py
Labels: priority3: urgent, sec: FCM, severity3: broken, type: bug/fix

#330 fix(fcm): Fix click_action to correct string
  other/models.py
Labels: sec: FCM, severity3: broken, type: bug/fix

#332 feat(device): Prevent refreshing from Firebase again within 12 hours
  helpers/device.py
  helpers/fcm.py
  other/migrations/0002_device_last_refresh.py
  other/models.py
  users/tests.py
Labels: sec: FCM, type: feature

#333 fix(venter): Prevent 500 on listing complaints for guest
  venter/views.py
Labels: sec: venter, severity2: inconvenient, type: bug/fix

#334 feat(users): Add show_contact_no to profile
  users/migrations/0028_userprofile_show_contact_no.py
  users/models.py
  users/serializer_full.py
  users/tests.py
Labels: model: UserProfile, type: feature

#335 fix(users): Add show_contact_no to serializer
  users/serializer_full.py
Labels: severity3: broken, type: bug/fix

#336 feat(login): Convert names to title case
  login/helpers.py
  login/test_server.py
Labels: sec: SSO, type: feature

#337 feat(upload): Add chore to clean unclaimed uploaded images
  upload/management/commands/clean-images.py
  upload/migrations/0005_auto_20190131_0018.py
  upload/models.py
  upload/tests.py
Labels: effort3: high, priority2: important, type: feature

#338 feat(upload): Add chore to clean media directory
  upload/management/commands/clean-images-files.py
Labels: type: feature, type: performance

#340 test(upload): Check if object can be deleted if file doesn't exist
  upload/tests.py
Labels: sec: testing, type: feature, type: refactor

#342 fix(fcm): Do not prefetch user, limit memory usage
  other/management/commands/push-notify.py
Labels: priority2: important, type: performance
